name: Test spurdo-as-a-service

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python-version: 3.8
        poetry_version: 1.0
        args: install
    - name: Run pytest
      with:
        python_version: 3.8.0
        poetry_version: 1.0
        args: run python -m pytest
